Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
 Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Max: 220

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 28

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/BlockLength:
  Max: 35

Layout/LineLength:
  Max: 165